version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    depends_on:
      - auth-mongo-srv
    volumes:
      - auth-data:/app/data
    env_file:
      - ./shared.env

  auth-mongo-srv:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./shared.env

  client:
    build: ./client
    ports:
      - "8080:3000"
    depends_on:
      - auth
    env_file:
      - ./shared.env
    volumes:
      - client-data:/app/.next

volumes:
  auth-data:
  mongo-data:
  client-data:

