version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    depends_on:
      - auth-mongo-srv
    volumes:
      - auth-data:/app/data
    env_file:
      - ./shared.env
    networks:
      - my_network

  auth-mongo-srv:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./shared.env
    networks:
      - my_network

  client:
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - auth
    env_file:
      - ./shared.env
    volumes:
      - client-data:/app/.next
    networks:
      - my_network

  tickets:
    build: ./tickets
    ports:
      - "3001:3001"  # Adjust the port as needed
    depends_on:
      - tickets-mongo-srv
    volumes:
      - tickets-data:/app/data
    env_file:
      - ./shared.env
    networks:
      - my_network

  tickets-mongo-srv:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: tickets
    ports:
      - "27018:27017"  # Adjust the port as needed
    volumes:
      - tickets-mongo-data:/data/db
    env_file:
      - ./shared.env
    networks:
      - my_network

volumes:
  auth-data:
  mongo-data:
  client-data:
  tickets-data:
  tickets-mongo-data:

