version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    depends_on:
      - auth-mongo-srv
    volumes:
      - auth-data:/app/data
    env_file:
      - ./shared.env
    networks:
      - my_network

  auth-mongo-srv:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./shared.env
    networks:
      - my_network

  client:
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - auth
    env_file:
      - ./shared.env
    volumes:
      - client-data:/app/.next
    networks:
      - my_network

  tickets:
    build: ./tickets
    ports:
      - "3001:3001"
    depends_on:
      - tickets-mongo-srv
      - rabbitmq
      - redis
    volumes:
      - tickets-data:/app/data
    env_file:
      - ./shared.env
    networks:
      - my_network

  tickets-mongo-srv:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: tickets
    ports:
      - "27018:27017"
    volumes:
      - tickets-mongo-data:/data/db
    env_file:
      - ./shared.env
    networks:
      - my_network

  rabbitmq:
    image: "rabbitmq:3.8"
    ports:
      - "5672:5672"
    networks:
      - my_network

  redis:
    image: "redis:latest"
    command: ["redis-server", "--maxmemory", "1g"]
    ports:
      - "6379:6379"
    networks:
      - my_network

  expiration:
    build: ./expiration
    depends_on:
      - rabbitmq
      - redis
      - tickets
    volumes:
      - ./expiration:/app
    networks:
      - my_network

volumes:
  auth-data:
  mongo-data:
  client-data:
  tickets-data:
  tickets-mongo-data:

