# keydb.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keydb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keydb
  template:
    metadata:
      labels:
        app: keydb
    spec:
      containers:
      - name: keydb
        image: eqalpha/keydb:latest
        args: ["keydb-server", "/etc/keydb/keydb.conf"]
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "1"    # Increased for better multithread performance
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: keydb-config
          mountPath: /etc/keydb
      volumes:
      - name: keydb-config
        configMap:
          name: keydb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keydb-config
data:
  keydb.conf: |
    server-threads 4
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    protected-mode no
    appendonly yes
---
apiVersion: v1
kind: Service
metadata:
  name: keydb-srv
spec:
  selector:
    app: keydb
  ports:
  - port: 6379
    targetPort: 6379
